#!/usr/bin/env python3
"""Generate the DeskBound battle from enemies.yaml.

GB Studio stores scripts as deeply nested JSON with UUIDs, so the whole
turn loop — one branch per enemy, per verb, per move — is miserable to author
in the GUI. This tool keeps the *content* in enemies.yaml and compiles it into
a single GB Studio custom script named "BattleScript".

It writes scripts and nothing else — no scene, no actors:

  project/scripts/battlescript.gbsres  the "BattleScript" turn loop
  project/scripts/battle_<enemy>.gbsres one per enemy, called by BattleScript
  project/scripts/setbar.gbsres        "SetBar" (only with "bars:")

A compiled script is one module and a module must fit in a single 16KB ROM
bank, so enemies cannot all live in BattleScript: at eight enemies it compiled
to 26KB and the linker refused it. Each enemy therefore gets its own script,
dispatched on a phase parameter (setup / act / look / flee / move / defeat),
and BattleScript keeps only the loop.

(--draw-bar-art additionally redraws the placeholder bar sprite in assets/.)

A GB Studio custom script cannot reference a scene actor by id — the compiler
rejects it with "Unknown arg actor ..." — so the actors the battle touches are
actor *parameters*: Enemy, and PlayerBar / EnemyBar when bars are configured.
Drop BattleScript into the battle scene's On Init and bind them from its
parameter dropdowns. Everything scene-side is yours.

The Energy bars are set by BattleScript through a second generated script,
"SetBar". They cannot poll instead: a scene's On Init script is compiled with
VM_LOCK, and while a context holds that lock the VM scheduler runs no other
thread, so an actor On Update script never executes during a battle.

Usage:
    python3 tools/gen_enemies.py [--enemies enemies.yaml] [--dry-run]
    python3 tools/gen_enemies.py --simulate      # play the generated script and
                                                 # report win rates per strategy
    python3 tools/gen_enemies.py --draw-bar-art  # redraw the placeholder bar
                                                 # strip after changing bars:

Everything else in the project stays hand-authored in the GB Studio GUI.
"""
import argparse
import glob
import json
import os
import random
import re
import sys
import uuid

try:
    import yaml
except ImportError:  # pragma: no cover - environment problem, not logic
    sys.exit("PyYAML is required: pip install pyyaml")

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

SCRIPT_NAME = "BattleScript"
SCRIPT_SYMBOL = "script_battle"
ENEMY_ACTOR_NAME = "Enemy"
# Custom-script actor parameter slots. Inside the script events reference an
# actor as "0"; the call site binds it with the arg key "$actor[0]$".
ENEMY_ACTOR_SLOT = "0"
PLAYER_BAR_SLOT = "1"
ENEMY_BAR_SLOT = "2"
PLAYER_BAR_NAME = "PlayerBar"
ENEMY_BAR_NAME = "EnemyBar"

# Each enemy compiles to its own custom script, because a compiled script is
# one module and a module must fit in a single 16KB ROM bank. With every enemy
# inlined, BattleScript hit 26KB at eight enemies. The turn loop stays here and
# calls into the enemy's script for the parts that carry the content.
ENEMY_SCRIPT_PREFIX = "Battle"
# Stamped into every generated script's description, so regeneration can clean
# up after a renamed enemy without touching anything hand-written.
GENERATED_MARK = "Generated by tools/gen_enemies.py from enemies.yaml."
ENEMY_PHASE_SLOT = "V0"
(PHASE_SETUP, PHASE_ACT, PHASE_LOOK,
 PHASE_FLEE, PHASE_MOVE, PHASE_DEFEAT, PHASE_NAME) = range(1, 8)

SETBAR_NAME = "SetBar"
SETBAR_SYMBOL = "script_setbar"
# SetBar's own parameter slots: the bar actor, plus value/max passed by value.
SETBAR_VALUE_SLOT = "V0"
SETBAR_MAX_SLOT = "V1"

# Globals the battle needs. They must already exist in project/variables.gbsres
# (create them in the GUI) — this tool never edits the variable list.
REQUIRED_VARS = [
    "enemy_id", "enemy_energy", "enemy_energy_max",
    "player_energy", "player_energy_max",
    "battle_menu_choice", "battle_act_choice", "battle_damage",
    "battle_temp", "battle_result", "battle_turn_count",
]

# Stats a win can raise, and the global each one moves. A reward is the only
# thing in the battle that *adds* to the player's Energy — everything else
# subtracts (see the note on ownership in enemies.yaml).
REWARD_VARS = {
    "energy": "player_energy",
    "max_energy": "player_energy_max",
    "brains": "player_brains",
}

# battle_result values, also readable from the overworld after the fight.
RESULT_ONGOING, RESULT_WIN, RESULT_FLED, RESULT_LOST = 0, 1, 2, 3

DEFAULT_MESSAGES = {
    # No running Energy totals: the bars show those. Define a "status"
    # message in enemies.yaml to bring a per-round text readout back.
    "hit": "It loses {damage}\nEnergy.",
    "no_effect": "It barely notices.",
    "player_hit": "You lose {damage}\nEnergy.",
}
DEFAULT_MENU = {"act": "ACT", "look": "LOOK", "flee": "FLEE"}
DEFAULT_FLEE = {
    "chance": 3,
    "out_of": 4,
    "success": "You walk away. The\nproblem remains, but\nso do you.",
    "failed": "You get as far as the\ndoor and change your\nmind.",
    "blocked": "You can't leave.",
}

MAX_VAR_VALUE = 32767  # GB Studio 4 globals are 16-bit

# Where the enemy's name is drawn, in background tiles — (0, 0) is the screen's
# top-left corner. EVENT_TEXT_DRAW's editor limits are x 0-19, y 0-17.
NAME_X, NAME_Y = 0, 0

# animSpeed is the engine's anim_tick. 255 is the editor's "None" — the only
# way to stop a sprite cycling its frames, since the `animate` flag is not
# emitted for actors in 4.2 and EVENT_ACTOR_SET_ANIMATE is deprecated and
# unimplemented. A bar actor whose frame *is* its value must be set to None in
# the GUI, or it animates on its own regardless of Energy.
ANIM_SPEED_NONE = 255


def fail(msg):
    raise SystemExit(f"gen_enemies: {msg}")


# ----------------------------------------------------------------- event JSON
# Ids are derived from a counter rather than random UUIDs so regenerating
# produces a stable diff instead of churning every id in the file.
_NS = uuid.UUID("d5f7a1e2-0000-4000-8000-000000000000")
_counter = {"n": 0}


def eid(tag=""):
    _counter["n"] += 1
    return str(uuid.uuid5(_NS, f"{tag}:{_counter['n']}"))


def ev(command, args=None, children=None):
    e = {"command": command, "args": args or {}, "id": eid(command)}
    if children:
        e["children"] = children
    return e


def num(v):
    return {"type": "number", "value": v}


def var(var_id):
    return {"type": "variable", "value": str(var_id)}


def add(a, b):
    return {"type": "add", "valueA": a, "valueB": b}


def sub(a, b):
    return {"type": "sub", "valueA": a, "valueB": b}


def mul(a, b):
    return {"type": "mul", "valueA": a, "valueB": b}


def div(a, b):
    return {"type": "div", "valueA": a, "valueB": b}


def rnd(a):
    return {"type": "rnd", "value": a}


def vmax(a, b):
    return {"type": "max", "valueA": a, "valueB": b}


def vmin(a, b):
    return {"type": "min", "valueA": a, "valueB": b}


def eq(a, b):
    return {"type": "eq", "valueA": a, "valueB": b}


def ne(a, b):
    return {"type": "ne", "valueA": a, "valueB": b}


def gt(a, b):
    return {"type": "gt", "valueA": a, "valueB": b}


def lt(a, b):
    return {"type": "lt", "valueA": a, "valueB": b}


def lte(a, b):
    return {"type": "lte", "valueA": a, "valueB": b}


def vand(a, b):
    return {"type": "and", "valueA": a, "valueB": b}


def _text(line):
    return ev("EVENT_TEXT", {
        "text": line,
        "avatarId": "",
        "clearPrevious": True,
    })


def text_draw(text, x, y):
    """Print onto the background tilemap — no box, no wait for a button.

    Unlike _text/EVENT_TEXT this doesn't block, and what it prints stays put
    until something else overwrites those tiles.

    That "until" is the catch, and it is not hypothetical. Drawn text and
    dialogue share one 52-tile glyph ring (ui.h's TEXT_BUFFER_START 0xCC to
    0xFF); ui_next_tile (ui.c) walks it forwards and wraps straight back to
    the start, and nothing resets it between messages. The tilemap here keeps
    pointing at its original tiles, so once the fight's dialogue has consumed
    52 tiles' worth of glyphs the ring laps and this text turns into pieces of
    whatever was said last. Redraw it if it has to survive a conversation.
    """
    return ev("EVENT_TEXT_DRAW",
              {"text": text, "x": x, "y": y, "location": "background"})


def make_say(roll_var):
    """Build the dialogue emitter, rolling variants on `roll_var`.

    A text field is a list of *variants*, each a list of steps. One variant is
    picked at random at runtime; its steps then play in order, one Display Text
    each. A single variant needs no roll at all.
    """

    def say(variants):
        if len(variants) == 1:
            return [_text(step) for step in variants[0]]
        cases = [(i, [_text(step) for step in variant])
                 for i, variant in enumerate(variants)]
        return ([set_var(roll_var, rnd(num(len(variants))))]
                + dispatch(var(roll_var), cases, catch_all=True))

    return say


def dispatch(value, cases, catch_all=False):
    """Nested if/else over `value` — cases are [(match, events), ...].

    Deliberately *not* a flat run of EVENT_IFs: only the taken branch is
    evaluated, so a branch is free to clobber the very variable being switched
    on. Dialogue variants and enemy move selection both roll `battle_temp`, and
    a flat chain would let a move's own text re-roll it into a second match.

    With catch_all the final case becomes the plain else — correct when the
    cases cover every value of a `rnd()`, and one comparison cheaper.
    """
    if not cases:
        return []
    node, rest = ([], cases) if not catch_all else (cases[-1][1], cases[:-1])
    for match, body in reversed(rest):
        node = [if_value(eq(value, num(match)), body, node)]
    return node


def set_var(var_id, value):
    return ev("EVENT_SET_VALUE", {"variable": str(var_id), "value": value})


def if_value(condition, true_children, false_children=None):
    return ev("EVENT_IF", {"condition": condition},
              {"true": true_children, "false": false_children or []})


def menu(var_id, items, layout="menu", cancel_on_b=False):
    args = {
        "variable": str(var_id),
        "items": len(items),
        "layout": layout,
        "cancelOnLastOption": False,
        "cancelOnB": cancel_on_b,
    }
    for i, label in enumerate(items):
        args[f"option{i + 1}"] = label
    return ev("EVENT_MENU", args)


def loop_while(condition, children):
    """The only loop GB Studio can exit — there is no break event."""
    return ev("EVENT_LOOP_WHILE", {"condition": condition}, {"true": children})


def actor_set_sprite(actor, sprite_id):
    return ev("EVENT_ACTOR_SET_SPRITE",
              {"actorId": actor, "spriteSheetId": sprite_id})


def actor_set_frame(actor, frame):
    return ev("EVENT_ACTOR_SET_FRAME", {"actorId": actor, "frame": frame})


def pop_state(fade_speed="2"):
    return ev("EVENT_SCENE_POP_STATE", {"fadeSpeed": fade_speed})


def call_custom(script_id, args=None):
    a = {"customEventId": script_id}
    a.update(args or {})
    return ev("EVENT_CALL_CUSTOM_EVENT", a)


def comment(body):
    return ev("EVENT_COMMENT", {"text": body})


# ------------------------------------------------------------------ project io
def load_json(path):
    with open(path) as f:
        return json.load(f)


def save_json(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(data, f, indent=2)


def load_variables():
    """name -> variable id, read from the project so ids can never drift."""
    path = os.path.join(ROOT, "project", "variables.gbsres")
    if not os.path.exists(path):
        fail(f"missing {path}")
    names = {}
    for v in load_json(path).get("variables", []):
        names[v["name"]] = v["id"]
    missing = [n for n in REQUIRED_VARS if n not in names]
    if missing:
        fail("project/variables.gbsres is missing required variables: "
             + ", ".join(missing))
    return names


SPRITE_DIR = os.path.join(ROOT, "assets", "sprites")


SCRIPTS_DIR = os.path.join(ROOT, "project", "scripts")


def load_scripts():
    """name -> custom script resource, for hooks written by hand in the GUI."""
    scripts = {}
    for path in glob.glob(os.path.join(SCRIPTS_DIR, "*.gbsres")):
        data = load_json(path)
        if data.get("_resourceType") == "script" and data.get("name"):
            scripts[data["name"]] = data
    return scripts


def load_sprites():
    """png file -> sprite sheet id, keyed the way enemies.yaml names sprites.

    The key is the path under assets/sprites/ ("actor.png", or
    "enemies/coffee.png" in a subfolder), not GB Studio's internal sprite
    *name*, so the YAML points at a file you can actually open.
    """
    sprites = {}
    pattern = os.path.join(SPRITE_DIR, "**", "*.png.gbsres")
    for sidecar in glob.glob(pattern, recursive=True):
        png = sidecar[:-len(".gbsres")]
        if not os.path.exists(png):
            continue  # sidecar without its image; GB Studio ignores it too
        sprites[os.path.relpath(png, SPRITE_DIR)] = load_json(sidecar)["id"]
    return sprites


# --------------------------------------------------------------- yaml loading
def var_ref(var_id):
    """Text interpolation token for a global, e.g. "$13$"."""
    return f"${int(var_id):02d}$" if str(var_id).isdigit() else f"${var_id}$"


class Substituter:
    """Replaces {damage}-style placeholders in any text with variable refs.

    Lets the YAML say "It loses {damage} Energy." instead of "$13$", which
    would otherwise bake variable *indices* into the writing.
    """

    def __init__(self, variables):
        self.tokens = {
            name: var_ref(variables[name]) for name in
            ("player_energy", "player_energy_max", "enemy_energy",
             "enemy_energy_max", "battle_turn_count", "enemy_id")
        }
        self.tokens["damage"] = var_ref(variables["battle_damage"])
        self.tokens["turn"] = var_ref(variables["battle_turn_count"])

    def __call__(self, body):
        if isinstance(body, list):
            return [self(line) for line in body]
        if not isinstance(body, str):
            fail(f"expected text, got {body!r}")
        return re.sub(r"\{(\w+)\}",
                      lambda m: self.tokens.get(m.group(1), m.group(0)), body)


def as_variants(value, where):
    """Normalise a text field to [[step, ...], ...] — variants of steps.

    Canonical form is a list of lists: one variant is picked at random, then
    its steps play in order. A flat list of strings is one variant with those
    steps, and a bare string is one variant with one step.
    """
    if isinstance(value, str):
        return [[value]]
    if not isinstance(value, list) or not value:
        fail(f"{where}: expected a non-empty list of dialogue variants")
    if all(isinstance(v, str) for v in value):
        return [list(value)]
    if not all(isinstance(v, list) for v in value):
        fail(f"{where}: mixes strings and lists — write every variant as its "
             "own list of steps")
    variants = []
    for i, variant in enumerate(value):
        if not variant or not all(isinstance(s, str) for s in variant):
            fail(f"{where}[{i}]: a variant must be a non-empty list of strings")
        variants.append(list(variant))
    return variants


def dialogue(value, where, subst):
    """Validate a text field's shape, then interpolate its placeholders."""
    return [[subst(step) for step in variant]
            for variant in as_variants(value, where)]


def parse_range(value, where):
    """Accept 5, "3-6" or [3, 6] and return an inclusive (lo, hi)."""
    if isinstance(value, bool):
        fail(f"{where}: expected a damage range, got {value!r}")
    if isinstance(value, int):
        lo = hi = value
    elif isinstance(value, str):
        m = re.fullmatch(r"\s*(\d+)\s*(?:-\s*(\d+)\s*)?", value)
        if not m:
            fail(f"{where}: bad damage range {value!r} (use 5 or \"3-6\")")
        lo = int(m.group(1))
        hi = int(m.group(2)) if m.group(2) else lo
    elif isinstance(value, list) and len(value) == 2 and all(
            isinstance(v, int) for v in value):
        lo, hi = value
    else:
        fail(f"{where}: bad damage range {value!r} (use 5, \"3-6\" or [3, 6])")
    if lo > hi:
        fail(f"{where}: damage range {value!r} is backwards")
    if hi > MAX_VAR_VALUE:
        fail(f"{where}: damage {hi} exceeds the 16-bit variable range")
    return lo, hi


def damage_value(lo, hi):
    """Script value for a uniform roll in [lo, hi]. rnd(n) yields 0..n-1."""
    if lo == hi:
        return num(lo)
    return add(num(lo), rnd(num(hi - lo + 1)))


def require(mapping, key, where):
    if key not in mapping:
        fail(f"{where}: missing required key '{key}'")
    return mapping[key]


class Effect:
    """One ACT verb's result against one enemy, or one enemy move."""

    def __init__(self, raw, where, subst):
        if isinstance(raw, dict):
            self.lo, self.hi = parse_range(require(raw, "damage", where), where)
            self.text = (dialogue(raw["text"], f"{where} text", subst)
                         if "text" in raw else None)
            unknown = set(raw) - {"damage", "text"}
            if unknown:
                fail(f"{where}: unknown keys {sorted(unknown)}")
        else:
            self.lo, self.hi = parse_range(raw, where)
            self.text = None


class Enemy:
    def __init__(self, raw, index, actions, sprites, subst):
        if not isinstance(raw, dict):
            fail(f"enemies[{index}]: expected a mapping")
        self.name = require(raw, "name", f"enemies[{index}]")
        where = f"enemy '{self.name}'"
        # Ids may start at 0, which suits an overworld that picks a fight with
        # a bare rnd(n). Left out, an id is the enemy's position in the list
        # counting from 1, so omitting ids never renumbers an existing project.
        self.id = raw.get("id", index + 1)
        if not isinstance(self.id, int) or isinstance(self.id, bool) \
                or self.id < 0:
            fail(f"{where}: id must be 0 or a positive integer")

        sprite_name = require(raw, "sprite", where)
        if sprite_name not in sprites:
            hint = ""
            if f"{sprite_name}.png" in sprites:
                hint = f" Did you mean '{sprite_name}.png'?"
            fail(f"{where}: no sprite file 'assets/sprites/{sprite_name}'."
                 f"{hint} Available: " + ", ".join(sorted(sprites)))
        self.sprite_id = sprites[sprite_name]
        self.sprite_name = sprite_name

        self.energy = require(raw, "energy", where)
        if not isinstance(self.energy, int) or not (
                0 < self.energy <= MAX_VAR_VALUE):
            fail(f"{where}: energy must be a positive integer")

        self.intro = dialogue(require(raw, "intro", where),
                              f"{where} intro", subst)
        self.look = dialogue(require(raw, "look", where),
                             f"{where} look", subst)
        self.defeat = dialogue(require(raw, "defeat", where),
                               f"{where} defeat", subst)

        take_damage = require(raw, "take_damage", where)
        if not isinstance(take_damage, dict):
            fail(f"{where}: take_damage must be a mapping of action -> damage")
        unknown = [a for a in take_damage if a not in actions]
        if unknown:
            fail(f"{where}: take_damage has actions not in the top-level "
                 f"'actions' list: {unknown}")
        missing = [a for a in actions if a not in take_damage]
        if missing:
            fail(f"{where}: take_damage is missing {missing}")
        self.take_damage = {
            action: Effect(take_damage[action],
                           f"{where} take_damage.{action}", subst)
            for action in actions
        }

        moves = require(raw, "moves", where)
        if not isinstance(moves, list) or not moves:
            fail(f"{where}: moves must be a non-empty list")
        self.moves = []
        for i, move in enumerate(moves):
            if not isinstance(move, dict) or "text" not in move:
                fail(f"{where} moves[{i}]: expected a mapping with 'text' "
                     "and 'damage'")
            self.moves.append(Effect(move, f"{where} moves[{i}]", subst))

        self.reward = self._read_reward(raw.get("reward"), where, subst)

        self.can_flee = raw.get("can_flee", True)
        self.flee_blocked = raw.get("flee_blocked")
        if self.flee_blocked:
            self.flee_blocked = dialogue(self.flee_blocked,
                                         f"{where} flee_blocked", subst)
        self.win_flag = raw.get("win_flag")

        unknown = set(raw) - {
            "id", "name", "sprite", "energy", "intro", "look", "defeat",
            "take_damage", "moves", "can_flee", "flee_blocked", "win_flag",
            "reward"}
        if unknown:
            fail(f"{where}: unknown keys {sorted(unknown)}")

    @staticmethod
    def _read_reward(reward, where, subst):
        """What beating this enemy gives back. Only applied on a win."""
        if not reward:
            return None
        if not isinstance(reward, dict):
            fail(f"{where} reward: expected a mapping of stat -> amount")
        unknown = set(reward) - set(REWARD_VARS) - {"text"}
        if unknown:
            fail(f"{where} reward: unknown keys {sorted(unknown)}. "
                 f"Stats: {', '.join(REWARD_VARS)}")
        out = {"text": dialogue(reward["text"], f"{where} reward.text", subst)
                       if "text" in reward else None}
        for stat in REWARD_VARS:
            if stat in reward:
                lo, hi = parse_range(reward[stat], f"{where} reward.{stat}")
                if hi < 1:
                    fail(f"{where} reward.{stat}: a reward must be able to "
                         "give at least 1")
                out[stat] = (lo, hi)
        if not any(stat in out for stat in REWARD_VARS) and not out["text"]:
            fail(f"{where} reward: empty — give a stat or some text, or drop "
                 "the key")
        return out


class Config:
    def __init__(self, raw, variables, sprites, scripts):
        if not isinstance(raw, dict):
            fail("enemies.yaml must be a mapping")
        subst = Substituter(variables)

        enemies_raw = require(raw, "enemies", "enemies.yaml")
        if not isinstance(enemies_raw, list) or not enemies_raw:
            fail("enemies.yaml: 'enemies' must be a non-empty list")

        self.actions = raw.get("actions")
        if self.actions is None:
            first = enemies_raw[0]
            self.actions = list(first.get("take_damage", {}))
        if not self.actions or not all(isinstance(a, str) for a in self.actions):
            fail("enemies.yaml: 'actions' must be a list of verb names")
        if len(self.actions) > 8:
            fail("enemies.yaml: GB Studio menus hold at most 8 options, "
                 f"got {len(self.actions)} actions")

        self.enemies = [Enemy(e, i, self.actions, sprites, subst)
                        for i, e in enumerate(enemies_raw)]
        seen_ids, seen_names = {}, {}
        for e in self.enemies:
            if e.id in seen_ids:
                fail(f"enemy id {e.id} used by both '{seen_ids[e.id]}' and "
                     f"'{e.name}'")
            seen_ids[e.id] = e.name
            if e.name in seen_names:
                fail(f"duplicate enemy name '{e.name}'")
            seen_names[e.name] = True

        self.messages = dict(DEFAULT_MESSAGES)
        self.messages.update(raw.get("messages") or {})
        self.messages = {k: dialogue(v, f"messages.{k}", subst)
                         for k, v in self.messages.items()}

        self.menu = dict(DEFAULT_MENU)
        self.menu.update(raw.get("menu") or {})

        self.flee = dict(DEFAULT_FLEE)
        self.flee.update(raw.get("flee") or {})
        if not isinstance(self.flee["out_of"], int) or self.flee["out_of"] < 1:
            fail("flee.out_of must be a positive integer")
        if not isinstance(self.flee["chance"], int) or not (
                0 <= self.flee["chance"] <= self.flee["out_of"]):
            fail("flee.chance must be between 0 and flee.out_of")
        for key in ("success", "failed", "blocked"):
            self.flee[key] = dialogue(self.flee[key], f"flee.{key}", subst)

        self.lose = dialogue(raw.get("lose") or [
            "You have run out of\nEnergy.",
            "You quietly gather\nyour things.",
        ], "lose", subst)

        for e in self.enemies:
            for stat in (e.reward or {}):
                if stat == "text":
                    continue
                if REWARD_VARS[stat] not in variables:
                    fail(f"enemy '{e.name}' reward.{stat}: needs a variable "
                         f"named '{REWARD_VARS[stat]}' in "
                         "project/variables.gbsres")

        self.win_flags = {}
        for e in self.enemies:
            if e.win_flag:
                if e.win_flag not in variables:
                    fail(f"enemy '{e.name}': win_flag '{e.win_flag}' is not a "
                         "variable in project/variables.gbsres")
                self.win_flags[e.id] = variables[e.win_flag]

        unknown = set(raw) - {"enemies", "actions", "messages",
                              "menu", "flee", "lose", "bars", "hooks"}
        if unknown:
            fail(f"enemies.yaml: unknown top-level keys {sorted(unknown)}")

        self.hooks = self._read_hooks(raw.get("hooks"), scripts)
        self.bars = self._read_bars(raw.get("bars"), sprites)

    def _read_hooks(self, hooks, scripts):
        """Optional hand-written scripts to call when the battle moves a value.

        Resolved by name from project/scripts/ so the script stays yours: this
        tool reads its parameter list and never rewrites it.
        """
        if not hooks:
            return {}
        if not isinstance(hooks, dict):
            fail("enemies.yaml: 'hooks' must be a mapping")
        supported = ("player_changed", "player_fainted")
        unknown = set(hooks) - set(supported)
        if unknown:
            fail(f"hooks: unknown keys {sorted(unknown)}. Supported: "
                 + ", ".join(supported))
        resolved = {}
        for key, name in hooks.items():
            if name is None:
                continue
            if name not in scripts:
                fail(f"hooks.{key}: no script named '{name}' in "
                     "project/scripts/. Available: "
                     + ", ".join(sorted(scripts)))
            script = scripts[name]
            if name in (SCRIPT_NAME, SETBAR_NAME):
                fail(f"hooks.{key}: '{name}' is generated by this tool — "
                     "calling it would recurse")
            # Hooks are called with no arguments, so anything the script
            # declares as a parameter would be left unbound — and an unbound
            # arg does not fail the GB Studio build, it silently compiles to
            # whichever variable the context defaults to.
            params = list(script.get("variables") or {}) + [
                f"actor {a}" for a in (script.get("actors") or {})]
            if params:
                fail(f"hooks.{key}: '{name}' declares parameters {params}, but "
                     "a hook is called with none — it reads globals directly. "
                     "In GB Studio, change the script to reference the global "
                     "variable instead of V0 and the parameter disappears.")
            resolved[key] = {"name": name, "id": script["id"]}
        return resolved

    def _read_bars(self, bars, sprites):
        """Optional Energy meters. Absent 'bars:' means none are generated.

        GB Studio has no hook that fires when a variable changes, so each bar
        is an actor that polls its variable in its own On Update script.
        """
        if not bars:
            return None
        if not isinstance(bars, dict):
            fail("enemies.yaml: 'bars' must be a mapping")
        sprite = require(bars, "sprite", "bars")
        if sprite not in sprites:
            fail(f"bars: no sprite file 'assets/sprites/{sprite}'. Available: "
                 + ", ".join(sorted(sprites)))
        frames = bars.get("frames", 17)
        if not isinstance(frames, int) or frames < 2:
            fail("bars.frames must be an integer of 2 or more (one sprite "
                 "frame per fill level, empty through full)")
        # frame = energy * (frames - 1) / max, computed in 16-bit ints.
        # Only the enemies can be checked here; the player's Energy is a
        # global set by the overworld, so keep it under this ceiling too.
        headroom = MAX_VAR_VALUE // (frames - 1)
        for e in self.enemies:
            if e.energy > headroom:
                fail(f"bars: enemy '{e.name}' energy {e.energy} × "
                     f"{frames - 1} frames overflows a 16-bit variable")
        unknown = set(bars) - {"sprite", "frames", "width", "height"}
        if unknown:
            fail(f"bars: unknown keys {sorted(unknown)}")
        return {
            "sprite": sprite,
            "sprite_id": sprites[sprite],
            "frames": frames,
        }


def build_setbar_script(cfg):
    """The "SetBar" custom script: show `value`/`max` on a bar actor.

    Kept as its own script rather than inlined so a hand-written script can
    refresh a bar too — drag SetBar in, pick the actor, pass the two values.
    """
    return [
        comment("Generated by tools/gen_enemies.py — sets a Energy bar's "
                "frame from a value and its maximum"),
        actor_set_frame("0", bar_fill_expression(cfg.bars["frames"],
                                                 SETBAR_VALUE_SLOT,
                                                 SETBAR_MAX_SLOT)),
    ]


def make_hook(cfg):
    """Emit a call to a hand-written hook.

    Hooks take no arguments: a custom script reads globals directly (only
    V0-V9 are parameters), so the hook just looks at player_energy itself.
    """

    def hook(key):
        spec = cfg.hooks.get(key)
        return [call_custom(spec["id"])] if spec else []

    return hook


def make_set_bar(cfg, V, setbar_id):
    """Emit a SetBar call, forwarding one of BattleScript's bar parameters."""

    def set_bar(slot, value_name, max_name):
        if not cfg.bars:
            return []
        return [call_custom(setbar_id, {
            f"$actor[0]$": slot,
            f"$variable[{SETBAR_VALUE_SLOT}]$": var(V[value_name]),
            f"$variable[{SETBAR_MAX_SLOT}]$": var(V[max_name]),
        })]

    return set_bar


# ----------------------------------------------------------- script generation
def make_emitters(cfg, V, setbar_id):
    """The pieces both builders need: dialogue, bars, hooks."""
    say = make_say(V["battle_temp"])
    set_bar = make_set_bar(cfg, V, setbar_id)
    hook = make_hook(cfg)

    def player_energy_changed():
        return (set_bar(PLAYER_BAR_SLOT, "player_energy", "player_energy_max")
                + hook("player_changed"))

    return say, set_bar, player_energy_changed, hook


def build_enemy_script(cfg, V, e, setbar_id):
    """One enemy's half of the fight, dispatched on a phase parameter.

    Everything that scales with the roster lives here — dialogue, per-verb
    responses, moves, the reward — so each enemy occupies its own module and
    therefore its own 16KB bank. BattleScript keeps only the turn loop.
    """
    say, set_bar, player_energy_changed, _ = make_emitters(cfg, V, setbar_id)

    # NAME: the name plate on its own, so BattleScript can put it back.
    # Every message and every menu takes its glyphs from the same 52-tile ring
    # (see text_draw), and the plate is drawn first, which makes it the first
    # thing the ring laps onto. Redrawing hands it fresh tiles at the point it
    # matters — BattleScript calls this phase at the top of each turn.
    name_plate = [text_draw(e.name, NAME_X, NAME_Y)]

    # SETUP: stats, sprite, name plate and the opening line.
    setup = [
        set_var(V["enemy_energy"], num(e.energy)),
        set_var(V["enemy_energy_max"], num(e.energy)),
        actor_set_sprite(ENEMY_ACTOR_SLOT, e.sprite_id),
    ] + name_plate + say(e.intro)

    # ACT: what each verb does to this enemy. Sets battle_damage; BattleScript
    # applies it, so the enemy bar and the hit line stay in one place.
    act_cases = []
    for i, action in enumerate(cfg.actions):
        effect = e.take_damage[action]
        body = say(effect.text) if effect.text else []
        body.append(set_var(V["battle_damage"],
                            damage_value(effect.lo, effect.hi)))
        act_cases.append((i + 1, body))
    act = dispatch(var(V["battle_act_choice"]), act_cases)

    # FLEE: a dice roll, or a flat refusal for an enemy you cannot leave.
    if e.can_flee:
        flee = [
            set_var(V["battle_temp"], rnd(num(cfg.flee["out_of"]))),
            if_value(
                lt(var(V["battle_temp"]), num(cfg.flee["chance"])),
                say(cfg.flee["success"])
                + [set_var(V["battle_result"], num(RESULT_FLED))],
                say(cfg.flee["failed"]),
            ),
        ]
    else:
        flee = say(e.flee_blocked or cfg.flee["blocked"])

    # MOVE: the enemy's turn.
    move_cases = []
    for i, move in enumerate(e.moves):
        hit = say(move.text) + [
            set_var(V["battle_damage"], damage_value(move.lo, move.hi)),
            set_var(V["player_energy"],
                    vmax(num(0), sub(var(V["player_energy"]),
                                     var(V["battle_damage"])))),
        ] + player_energy_changed()
        hit.append(if_value(gt(var(V["battle_damage"]), num(0)),
                            say(cfg.messages["player_hit"])))
        move_cases.append((i, hit))
    # catch_all: the roll covers every move, and a move's own dialogue may
    # re-roll battle_temp, so the last case must not be re-tested.
    moves = ([set_var(V["battle_temp"], rnd(num(len(e.moves))))]
             + dispatch(var(V["battle_temp"]), move_cases, catch_all=True))

    defeat = say(e.defeat) + reward_events(cfg, V, e, say,
                                           player_energy_changed)
    if e.id in cfg.win_flags:
        defeat.append(set_var(cfg.win_flags[e.id], num(1)))

    return [
        comment(f"{e.name} — generated by tools/gen_enemies.py from "
                "enemies.yaml; edits here will be overwritten"),
    ] + dispatch(var(ENEMY_PHASE_SLOT), [
        (PHASE_SETUP, setup),
        (PHASE_ACT, act),
        (PHASE_NAME, name_plate),
        (PHASE_LOOK, say(e.look)),
        (PHASE_FLEE, flee),
        (PHASE_MOVE, moves),
        (PHASE_DEFEAT, defeat),
    ])


def reward_events(cfg, V, e, say, player_energy_changed):
    """Apply a win's stat gains, then show the flavour line.

    Order matters: the gains land before the text, so the bar has already
    grown by the time the player reads about it. A max_energy gain raises
    current Energy by the same amount, so widening the tank never leaves the
    bar looking emptier than it was a moment ago.
    """
    reward = e.reward
    if not reward:
        return []

    def amount(stat):
        """The gain as a script value, rolling a range into battle_temp.

        battle_temp is free here — the fight is over and nothing is
        dispatching on it — but a range must be rolled once and reused, not
        re-rolled per use.
        """
        lo, hi = reward[stat]
        if lo == hi:
            return [], num(lo)
        return ([set_var(V["battle_temp"], damage_value(lo, hi))],
                var(V["battle_temp"]))

    out, touched_energy = [], False
    if "max_energy" in reward:
        roll, value = amount("max_energy")
        out += roll + [
            set_var(V["player_energy_max"],
                    add(var(V["player_energy_max"]), value)),
            # same amount into current Energy, so the bar keeps its fill
            set_var(V["player_energy"], add(var(V["player_energy"]), value)),
        ]
        touched_energy = True
    if "energy" in reward:
        roll, value = amount("energy")
        out += roll + [
            set_var(V["player_energy"],
                    vmin(var(V["player_energy_max"]),
                         add(var(V["player_energy"]), value))),
        ]
        touched_energy = True
    if "brains" in reward:
        roll, value = amount("brains")
        out.append(set_var(V["player_brains"],
                           add(var(V["player_brains"]), value)))
    if touched_energy:
        out += player_energy_changed()
    if reward["text"]:
        out += say(reward["text"])
    return out


def build_battle_script(cfg, V, setbar_id, enemy_script_ids):
    """The turn loop. Everything enemy-specific is a call into its script."""
    say, set_bar, player_energy_changed, hook = make_emitters(
        cfg, V, setbar_id)

    def enemy_phase(phase):
        """Branch on enemy_id and run that enemy's script at `phase`."""
        args = {f"$actor[{ENEMY_ACTOR_SLOT}]$": ENEMY_ACTOR_SLOT,
                f"$variable[{ENEMY_PHASE_SLOT}]$": num(phase)}
        if cfg.bars:
            args[f"$actor[{PLAYER_BAR_SLOT}]$"] = PLAYER_BAR_SLOT
        return dispatch(var(V["enemy_id"]),
                        [(e.id, [call_custom(enemy_script_ids[e.id], args)])
                         for e in cfg.enemies])

    s = [comment("Generated by tools/gen_enemies.py from enemies.yaml — "
                 "edits made here will be overwritten")]

    # --- setup: look up the enemy the overworld asked for -------------------
    s.append(comment("Load enemy from enemy_id"))
    s += enemy_phase(PHASE_SETUP)
    s += set_bar(ENEMY_BAR_SLOT, "enemy_energy", "enemy_energy_max")

    s += [
        # player_energy / player_energy_max are NOT set here: they are
        # global, owned by the overworld, and carry across battles.
        set_var(V["battle_turn_count"], num(0)),
        set_var(V["battle_result"], num(RESULT_ONGOING)),
    ] + player_energy_changed()

    # --- one round ----------------------------------------------------------
    turn = [
        set_var(V["battle_turn_count"],
                add(var(V["battle_turn_count"]), num(1))),
        set_var(V["battle_damage"], num(0)),
        # "status" is optional and unset by default — the bars report Energy.
        *(say(cfg.messages["status"]) if "status" in cfg.messages else []),
        # Repaint the name plate last, so it holds the newest tiles in the
        # glyph ring when the menu opens. The menu's own labels are far short
        # of a full lap, so the plate survives the one screen the player
        # actually sits and looks at.
        *enemy_phase(PHASE_NAME),
        menu(V["battle_menu_choice"],
             [cfg.menu["act"], cfg.menu["look"], cfg.menu["flee"]],
             layout="menu"),
    ]

    act = [menu(V["battle_act_choice"], cfg.actions, layout="dialogue")]
    act += enemy_phase(PHASE_ACT)
    act += [
        set_var(V["enemy_energy"],
                vmax(num(0), sub(var(V["enemy_energy"]),
                                 var(V["battle_damage"])))),
    ] + set_bar(ENEMY_BAR_SLOT, "enemy_energy", "enemy_energy_max") + [
        if_value(gt(var(V["battle_damage"]), num(0)),
                 say(cfg.messages["hit"]),
                 say(cfg.messages["no_effect"])),
    ]

    turn.append(if_value(
        eq(var(V["battle_menu_choice"]), num(1)), act,
        [if_value(eq(var(V["battle_menu_choice"]), num(2)),
                  enemy_phase(PHASE_LOOK), enemy_phase(PHASE_FLEE))]))

    # Win check runs before the enemy replies, so a killing blow ends it.
    turn.append(if_value(lte(var(V["enemy_energy"]), num(0)),
                         [set_var(V["battle_result"], num(RESULT_WIN))]))

    # --- enemy turn (skipped after LOOK, a successful flee, or a win) -------
    turn.append(if_value(
        vand(ne(var(V["battle_menu_choice"]), num(2)),
             eq(var(V["battle_result"]), num(RESULT_ONGOING))),
        enemy_phase(PHASE_MOVE)))

    turn.append(if_value(lte(var(V["player_energy"]), num(0)),
                         [set_var(V["battle_result"], num(RESULT_LOST))]))

    s.append(loop_while(eq(var(V["battle_result"]), num(RESULT_ONGOING)), turn))

    # --- resolution ---------------------------------------------------------
    # Out of Energy: say the line, then hand over to the overworld's hook —
    # which is where going home and sleeping belongs (DESIGN.md 9.2). If that
    # hook switches scenes, the pop below never runs: a scene change kills
    # every running script.
    lost = say(cfg.lose) + hook("player_fainted")

    s.append(if_value(
        eq(var(V["battle_result"]), num(RESULT_WIN)), enemy_phase(PHASE_DEFEAT),
        [if_value(eq(var(V["battle_result"]), num(RESULT_LOST)), lost)]))

    # Return to whichever scene pushed its state before the fight.
    s.append(pop_state())
    return s


# ------------------------------------------------------------------- emitting
_ID_NS = uuid.UUID("d5f7a1e2-2222-4000-8000-000000000000")


def stable_id(key):
    return str(uuid.uuid5(_ID_NS, key))


def write_setbar_resource(cfg, dry_run):
    """The SetBar custom script — only written when bars are configured."""
    if not cfg.bars:
        return None, None
    setbar_id = stable_id("setbar")
    resource = {
        "_resourceType": "script",
        "id": setbar_id,
        "name": SETBAR_NAME,
        "description": GENERATED_MARK,
        "variables": {
            SETBAR_VALUE_SLOT: {"id": SETBAR_VALUE_SLOT, "name": "Value",
                                "passByReference": False},
            SETBAR_MAX_SLOT: {"id": SETBAR_MAX_SLOT, "name": "Max",
                              "passByReference": False},
        },
        "actors": {"0": {"id": "0", "name": "Bar"}},
        "symbol": SETBAR_SYMBOL,
        "script": build_setbar_script(cfg),
    }
    path = os.path.join(ROOT, "project", "scripts", "setbar.gbsres")
    if not dry_run:
        save_json(path, resource)
    return setbar_id, path


def write_enemy_resources(cfg, V, setbar_id, dry_run):
    """One custom script per enemy — each its own module, so its own bank."""
    ids, paths, events, stale, written = {}, [], {}, [], set()
    actors = {ENEMY_ACTOR_SLOT: {"id": ENEMY_ACTOR_SLOT,
                                 "name": ENEMY_ACTOR_NAME}}
    if cfg.bars:
        actors[PLAYER_BAR_SLOT] = {"id": PLAYER_BAR_SLOT,
                                   "name": PLAYER_BAR_NAME}
    for e in cfg.enemies:
        name = f"{ENEMY_SCRIPT_PREFIX} {e.name}"
        script_id = stable_id(f"enemy_script_{e.id}")
        resource = {
            "_resourceType": "script",
            "id": script_id,
            "name": name,
            "description": f"{e.name}'s half of the battle. {GENERATED_MARK}",
            "variables": {ENEMY_PHASE_SLOT: {"id": ENEMY_PHASE_SLOT,
                                             "name": "Phase",
                                             "passByReference": False}},
            "actors": actors,
            "symbol": f"script_enemy_{e.id}",
            "script": build_enemy_script(cfg, V, e, setbar_id),
        }
        path = os.path.join(ROOT, "project", "scripts",
                            f"{slugify(name)}.gbsres")
        if not dry_run:
            save_json(path, resource)
        ids[e.id] = script_id
        events[script_id] = resource["script"]
        paths.append((name, path))
        written.add(os.path.abspath(path))

    # Renaming or removing an enemy would otherwise leave its script behind,
    # still compiling into a bank of its own. Only files this tool stamped are
    # ever removed — a hand-written script that happens to start with the same
    # word is left alone.
    for path in glob.glob(os.path.join(SCRIPTS_DIR, "*.gbsres")):
        if os.path.abspath(path) in written:
            continue
        data = load_json(path)
        if data.get("description", "").endswith(GENERATED_MARK) and \
                data.get("name", "").startswith(ENEMY_SCRIPT_PREFIX + " "):
            stale.append(os.path.relpath(path, ROOT))
            if not dry_run:
                os.remove(path)
    return ids, paths, events, stale


def write_script_resource(cfg, V, setbar_id, enemy_script_ids, dry_run):
    script_id = stable_id("battlescript")
    actors = {ENEMY_ACTOR_SLOT: {"id": ENEMY_ACTOR_SLOT,
                                 "name": ENEMY_ACTOR_NAME}}
    if cfg.bars:
        actors[PLAYER_BAR_SLOT] = {"id": PLAYER_BAR_SLOT,
                                   "name": PLAYER_BAR_NAME}
        actors[ENEMY_BAR_SLOT] = {"id": ENEMY_BAR_SLOT,
                                  "name": ENEMY_BAR_NAME}
    resource = {
        "_resourceType": "script",
        "id": script_id,
        "name": SCRIPT_NAME,
        "description": GENERATED_MARK,
        "variables": {},
        "actors": actors,
        "symbol": SCRIPT_SYMBOL,
        "script": build_battle_script(cfg, V, setbar_id, enemy_script_ids),
    }
    path = os.path.join(ROOT, "project", "scripts", "battlescript.gbsres")
    if not dry_run:
        save_json(path, resource)
    return script_id, path, resource["script"]


# Placeholder bar art. GB Studio sprite tiles are 8x16, so a bar cell is
# CELL_H tall and its width must divide into 8px columns.
CELL_H = 16
BAR_TRANSPARENT = (101, 255, 0)   # #65FF00 — GB Studio's sprite colour key
BAR_DARK = (7, 24, 33)
BAR_FILL = (134, 192, 108)
BAR_EMPTY = (224, 248, 207)
_ART_NS = uuid.UUID("d5f7a1e2-3333-4000-8000-000000000000")


def draw_bar_art(bars, dry_run):
    """Redraw the placeholder bar strip and its sprite sidecar from `bars:`.

    Separate from the normal run because the art is an *asset*: once drawn (or
    replaced with real art at the same dimensions) it just sits in
    assets/sprites/ like any other sprite. Regenerate when the width, height or
    frame count changes.
    """
    try:
        from PIL import Image
    except ImportError:
        fail("--draw-bar-art needs Pillow: pip install pillow")

    if not isinstance(bars, dict):
        fail("--draw-bar-art needs a 'bars:' section in enemies.yaml")
    name = require(bars, "sprite", "bars")
    frames = bars.get("frames", 17)
    width = bars.get("width", 64)
    height = bars.get("height", 8)
    if not isinstance(width, int) or width % 8 or not (8 <= width <= 160):
        fail("bars.width must be a multiple of 8 between 8 and 160 (the "
             "screen is 160px; each 8px column costs one hardware sprite)")
    if not isinstance(height, int) or not (2 <= height <= CELL_H):
        fail(f"bars.height must be between 2 and {CELL_H}")
    if not isinstance(frames, int) or frames < 2:
        fail("bars.frames must be an integer of 2 or more")

    steps = frames - 1
    top = (CELL_H - height) // 2
    img = Image.new("RGB", (width * frames, CELL_H), BAR_TRANSPARENT)
    px = img.load()
    for k in range(frames):
        ox = k * width
        filled = width * k // steps
        for x in range(width):
            px[ox + x, top] = BAR_DARK                  # top rule
            px[ox + x, top + height - 1] = BAR_DARK     # bottom rule
            for y in range(top + 1, top + height - 1):
                px[ox + x, y] = BAR_FILL if x < filled else BAR_EMPTY

    columns = width // 8

    # numTiles is taken at face value by both the editor's "sprite tiles used"
    # counter and the compiler's per-scene budget (compileData's
    # getSpriteTileCount reads the resource; nothing recomputes it from the
    # image). Count what GB Studio will actually keep: unique 8x16 tiles after
    # deduplication, matching readSpriteData's flip-aware comparison.
    def unique_tile_count():
        seen = []
        for k in range(frames):
            for col in range(columns):
                ox = k * width + col * 8
                tile = tuple(tuple(px[ox + x, y] for x in range(8))
                             for y in range(CELL_H))
                flips = {tile,
                         tuple(row[::-1] for row in tile),
                         tuple(tile[::-1]),
                         tuple(row[::-1] for row in tile[::-1])}
                if not any(t in seen for t in flips):
                    seen.append(tile)
        return len(seen)

    png_path = os.path.join(SPRITE_DIR, name)
    sidecar_path = png_path + ".gbsres"
    sid = lambda k: str(uuid.uuid5(_ART_NS, f"{name}:{k}"))

    # Tile x/y are ORIGIN-relative, not canvas-relative. GB Studio's tile
    # optimiser masks each tile at (originX + x, originY - y) against a
    # canvas-sized image, where originX = canvasWidth / 2 - 8 (readSpriteData.ts)
    # — so a canvas-relative x pushes the right-hand tiles outside the mask,
    # where they are marked Unknown, and Unknown matches *any* tile during
    # deduplication. Every frame then renders as the same scrambled tiles.
    # (At canvasWidth 16 originX is 0 and the two conventions coincide, which
    # is why a narrow bar worked.)
    origin_x = 0 if width < 16 else width // 2 - 8

    def tile(k, col):
        return {"id": sid(f"tile{k}.{col}"), "x": col * 8 - origin_x, "y": 0,
                "sliceX": k * width + col * 8, "sliceY": 0,
                "flipX": False, "flipY": False, "palette": 0,
                "paletteIndex": 0, "objPalette": "OBP0", "priority": False}

    # A "fixed" state still carries eight animation slots; only the first runs.
    animations = [{"id": sid("anim0"), "frames": [
        {"id": sid(f"frame{k}"), "tiles": [tile(k, c) for c in range(columns)]}
        for k in range(frames)]}]
    animations += [{"id": sid(f"anim{i}"),
                    "frames": [{"id": sid(f"empty{i}"), "tiles": []}]}
                   for i in range(1, 8)]

    sprite = {
        "_resourceType": "sprite",
        "id": sid("sprite"),
        "name": name[:-len(".png")] if name.endswith(".png") else name,
        "symbol": "sprite_" + slugify(name.rsplit(".", 1)[0]),
        "states": [{"id": sid("state"), "name": "", "animationType": "fixed",
                    "flipLeft": False, "animations": animations}],
        "numTiles": unique_tile_count(),
        "canvasOriginX": 0, "canvasOriginY": 0,
        "canvasWidth": width, "canvasHeight": CELL_H,
        "boundsX": 0, "boundsY": 0,
        "boundsWidth": width, "boundsHeight": height,
        "animSpeed": ANIM_SPEED_NONE,
        "filename": name,
        # GB Studio recomputes width/height/checksum/inode on load; the frame
        # slicing above is what it keeps.
        "width": width * frames, "height": CELL_H, "checksum": "",
    }
    if not dry_run:
        os.makedirs(os.path.dirname(png_path), exist_ok=True)
        img.convert("P", palette=Image.ADAPTIVE, colors=4).save(png_path)
        save_json(sidecar_path, sprite)
    return png_path, frames, width, columns


def slugify(name):
    """GB Studio's resource filename rule: lowercase, spaces to underscores."""
    return re.sub(r"[^a-z0-9_]", "_", name.lower().replace(" ", "_"))


def bar_fill_expression(frames, value_var, max_var):
    """Frame index for a Energy value: which fill level to show.

    Ceiling, not truncation: (value * steps + divisor - 1) / divisor, so a
    player on 1 Energy still shows a sliver and only a real 0 reads empty.
    The divisor is floored at 1 so the bar is harmless before a maximum is set.
    """
    divisor = vmax(num(1), var(max_var))
    return div(add(mul(var(value_var), num(frames - 1)), sub(divisor, num(1))),
               divisor)


# ------------------------------------------------------------------ simulation
# Balance is checked by *interpreting the generated event tree* rather than by
# re-implementing the damage rules, so what gets measured is what ships.
def _eval(value, V):
    kind = value["type"]
    if kind == "number":
        return value["value"]
    if kind == "variable":
        return V.get(value["value"], 0)
    if kind == "rnd":
        return random.randrange(_eval(value["value"], V))
    a, b = _eval(value["valueA"], V), _eval(value["valueB"], V)
    ops = {
        "add": lambda: a + b, "sub": lambda: a - b,
        "max": lambda: max(a, b), "min": lambda: min(a, b),
        "mul": lambda: a * b,
        # GBVM divides integers, truncating; the generator floors divisors at 1.
        "div": lambda: a // b if b else 0,
        "eq": lambda: int(a == b), "ne": lambda: int(a != b),
        "gt": lambda: int(a > b), "lt": lambda: int(a < b),
        "lte": lambda: int(a <= b), "and": lambda: int(bool(a) and bool(b)),
    }
    if kind not in ops:
        fail(f"simulation: unhandled script value '{kind}'")
    return ops[kind]()


def _run(events, V, choose, budget, scripts=None):
    """Interpret generated events. `scripts` maps a custom script id to its
    events, so calls into the per-enemy scripts are followed; anything else
    (SetBar, hooks) only moves sprites, so it is skipped."""
    scripts = scripts or {}
    for e in events:
        command, args = e["command"], e.get("args", {})
        children = e.get("children", {})
        if command == "EVENT_SET_VALUE":
            V[args["variable"]] = _eval(args["value"], V)
        elif command == "EVENT_IF":
            branch = "true" if _eval(args["condition"], V) else "false"
            _run(children.get(branch, []), V, choose, budget, scripts)
        elif command == "EVENT_LOOP_WHILE":
            while _eval(args["condition"], V):
                budget["turns"] -= 1
                if budget["turns"] < 0:
                    raise RuntimeError("battle never ended")
                _run(children["true"], V, choose, budget, scripts)
        elif command == "EVENT_MENU":
            options = [args[f"option{i + 1}"] for i in range(args["items"])]
            V[args["variable"]] = choose(args["variable"], options)
        elif command == "EVENT_SCENE_POP_STATE":
            return
        elif command == "EVENT_CALL_CUSTOM_EVENT":
            target = scripts.get(args["customEventId"])
            if target:
                phase_arg = args.get(f"$variable[{ENEMY_PHASE_SLOT}]$")
                saved = V.get(ENEMY_PHASE_SLOT)
                V[ENEMY_PHASE_SLOT] = _eval(phase_arg, V) if phase_arg else 0
                _run(target, V, choose, budget, scripts)
                if saved is None:
                    V.pop(ENEMY_PHASE_SLOT, None)
                else:
                    V[ENEMY_PHASE_SLOT] = saved
        elif command not in ("EVENT_TEXT", "EVENT_TEXT_DRAW", "EVENT_COMMENT",
                             "EVENT_ACTOR_SET_SPRITE",
                             "EVENT_ACTOR_SET_FRAME"):
            fail(f"simulation: unhandled event '{command}'")


def simulate(cfg, V, script, runs, player_energy, scripts):
    """Win rate and average turn count per strategy, per enemy."""
    strategies = ["random"] + list(cfg.actions)
    width = max(12, max(len(s) for s in strategies) + 6)
    header = f"{'enemy':>16}" + "".join(f"{s:>{width}}" for s in strategies)
    print("\nbalance (%d games per cell, player starting on %d Energy)\n%s"
          % (runs, player_energy, header))

    for enemy in cfg.enemies:
        row = f"{enemy.name:>16}"
        for strategy in strategies:
            wins, turns = 0, 0
            for _ in range(runs):
                state = {V["enemy_id"]: enemy.id,
                         V["player_energy"]: player_energy,
                         V["player_energy_max"]: player_energy}

                def choose(variable, options, strategy=strategy):
                    if variable == V["battle_menu_choice"]:
                        return 1  # always ACT
                    if strategy == "random":
                        return random.randrange(1, len(options) + 1)
                    return options.index(strategy) + 1

                _run(script, state, choose, {"turns": 500}, scripts)
                wins += state[V["battle_result"]] == RESULT_WIN
                turns += state[V["battle_turn_count"]]
            row += f"{100 * wins / runs:>{width - 6}.1f}% {turns / runs:>4.1f}t"
        print(row)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--enemies", default=os.path.join(ROOT, "enemies.yaml"),
                    help="path to enemies.yaml (default: repo root)")
    ap.add_argument("--dry-run", action="store_true",
                    help="validate and report without writing any file")
    ap.add_argument("--player-energy", type=int, default=100, metavar="N",
                    help="starting Energy to assume when simulating; the "
                         "battle itself reads the global, which the overworld "
                         "owns (default 100)")
    ap.add_argument("--draw-bar-art", action="store_true",
                    help="redraw the placeholder Energy bar strip and its "
                         "sprite sidecar from the 'bars:' section, then carry "
                         "on as normal")
    ap.add_argument("--simulate", nargs="?", type=int, const=2000,
                    metavar="RUNS",
                    help="play the generated script RUNS times per strategy "
                         "and report win rates (default 2000)")
    args = ap.parse_args()

    if not os.path.exists(args.enemies):
        fail(f"no such file: {args.enemies}")
    with open(args.enemies) as f:
        raw = yaml.safe_load(f)

    if args.draw_bar_art:
        png, frames, width, columns = draw_bar_art(raw.get("bars"),
                                                   args.dry_run)
        print(f"{'would draw' if args.dry_run else 'drew'} "
              f"{os.path.relpath(png, ROOT)}  ({frames} frames, {width}px "
              f"wide = {columns} hardware sprites per bar)")

    variables = load_variables()
    sprites = load_sprites()
    if not sprites:
        fail("no sprites found under assets/sprites/")
    cfg = Config(raw, variables, sprites, load_scripts())
    V = {name: variables[name] for name in REQUIRED_VARS}
    # Reward stats are only needed when an enemy actually grants them; Config
    # has already checked that each one exists in the project.
    for enemy in cfg.enemies:
        for stat in (enemy.reward or {}):
            if stat != "text":
                V[REWARD_VARS[stat]] = variables[REWARD_VARS[stat]]

    setbar_id, setbar_path = write_setbar_resource(cfg, args.dry_run)
    (enemy_script_ids, enemy_paths, enemy_scripts,
     stale_paths) = write_enemy_resources(cfg, V, setbar_id, args.dry_run)
    script_id, script_path, script = write_script_resource(
        cfg, V, setbar_id, enemy_script_ids, args.dry_run)

    prefix = "would write" if args.dry_run else "wrote"
    rel = lambda p: os.path.relpath(p, ROOT)
    print(f"{prefix} {rel(script_path)}  ({SCRIPT_NAME}, "
          f"{len(cfg.enemies)} enemies, {len(cfg.actions)} actions)")
    if setbar_path:
        print(f"{prefix} {rel(setbar_path)}  ({SETBAR_NAME}: bar actor, "
              "value, max)")
    for name, path in enemy_paths:
        print(f"{prefix} {rel(path)}  ({name})")
    for path in stale_paths:
        print(f"{'would remove' if args.dry_run else 'removed'} {path}  "
              "(no enemy with that name any more)")
    if cfg.bars:
        print(f"  bars: {cfg.bars['sprite']}, {cfg.bars['frames']} frames, "
              f"set via {SETBAR_NAME} at each Energy change")
    when = {"player_changed": "after every write to player_energy",
            "player_fainted": "when Energy runs out, after the lose text"}
    for key, spec in cfg.hooks.items():
        print(f"  hook {key}: calls {spec['name']}() {when[key]}")
    print("  the overworld owns player_energy and player_energy_max — "
          "BattleScript subtracts damage and adds rewards, never sets them")
    print(f"  wire it in GB Studio: add {SCRIPT_NAME} to the battle scene's "
          "On Init, then bind its actor parameters —")
    print(f"    {ENEMY_ACTOR_NAME} -> the actor whose sprite the fight swaps "
          "per enemy")
    if cfg.bars:
        print(f"    {PLAYER_BAR_NAME} / {ENEMY_BAR_NAME} -> two actors using "
              f"{cfg.bars['sprite']}, each with Animation Speed: None")
    if any(e.id == 0 for e in cfg.enemies):
        zero = next(e.name for e in cfg.enemies if e.id == 0)
        print(f"  note: '{zero}' is enemy 0, and a GB Studio variable starts "
              "at 0 — an unset enemy_id will pick this fight")
    for e in cfg.enemies:
        flags = "" if e.can_flee else ", no flee"
        gains = ", ".join(
            f"+{lo}" + (f"-{hi}" if hi != lo else "") + f" {stat}"
            for stat, (lo, hi) in sorted(
                (k, v) for k, v in (e.reward or {}).items() if k != "text"))
        print(f"  #{e.id} {e.name}: energy {e.energy}, "
              f"sprite {e.sprite_name}, {len(e.moves)} moves{flags}"
              + (f", reward {gains}" if gains else ""))

    if args.simulate:
        simulate(cfg, V, script, args.simulate, args.player_energy,
                 enemy_scripts)


if __name__ == "__main__":
    main()
